name: "Build Docker image"
on:
  [workflow_dispatch]

permissions:
  contents: read
  packages: write

jobs:
  get_date:
    name: Get build start date
    runs-on: ubuntu-latest
    outputs:
      IMG_DATE: ${{ steps.date.outputs.IMG_DATE }}
    steps:
      - name: Get current date in RFC 3339
        id: date
        run: |
          IMG_DATE=$(date --rfc-3339=seconds | sed 's/ /T/')
          echo "IMG_DATE=${IMG_DATE}" >> $GITHUB_OUTPUT
          echo "The date is $IMG_DATE"

  build_push:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: get_date
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image for amd64/arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          build-args: |
            IMAGE_BUILD_DATE=${{ needs.get_date.outputs.IMG_DATE }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/orbit:latest